### ISSUE TITLE
[ToDo] Review all variables and their defaults in NTuplizer

### ISSUE THREAD

**Issue by reimersa** [LEAF-HQ/LEAF#59]
### Current situation and requested solution
Some variables in the NTuples are not filled sensibly, defaults are sometimes inconsistent (-1, -9, -99, ...). 
Review every single variable (they are not too many) filled in the NTuples and make sure they are filled properly, make sense, and are useful. 
Also compare "standalone" version of NTuplizer to new CMSSW-based version to make sure there are no unexpected changes.

### To be done after
- [ ] #16 

### To be done before
- [ ] #14 

### Steps
- [ ] Review code
- [ ] synchronize defaults (but do not rely on the exact value anywhere)
- [ ] Verify proper and as-expected filling of all variables in example tuples 
  - [ ] in data
  - [ ] in MC
- [ ] Compare to NTuples produced with old `Tuplizer_MINIAOD` and make sure there are no unexpected changes

### References
- list of links and additional into relevant to this issue
