### ISSUE TITLE
[ToDo] Download genproductions repository during setup

### ISSUE THREAD

**Issue by reimersa** [LEAF-HQ/LEAF#76]
### Current situation and requested solution
A fresh setup of LEAF is missing the CMSSW genproductions repository (https://github.com/cms-sw/genproductions) to produce gridpacks.

### To be done after
- nothing

### To be done before
- nothing

### Steps
- [ ] modify setup script to download https://github.com/cms-sw/genproductions
- [ ] make necessary changes to PDF files to store systematic weights of all recommended ones
- [ ] make changes to `gridpack_generation.sh` to work with `LEAF/Generator`

### References
- general info: https://twiki.cern.ch/twiki/bin/view/CMS/QuickGuideMadGraph5aMCatNLO
